### ISSUE TITLE
New version, use git yaml for now 

### ISSUE THREAD

**Issue by realitymolder** [MarcelGarus/marquee#109]
Due to the fact that I still dont have permissons for pub.dev, please use the following in your project pubspec.yaml file.

```yaml
  marquee:
    git:
      url: https://github.com/MarcelGarus/marquee.git
      ref: "master"
```
