### ISSUE TITLE
error build for flutter 3.22.0

### ISSUE THREAD

**Issue by mdddj** [MarcelGarus/marquee#95]
```dart
Could not build the precompiled application for the device.
Error (Xcode): ../.pub-cache/hosted/pub.dev/fading_edge_scrollview-3.0.0/lib/src/fading_edge_scrollview.dart:116:31: Error: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController' because 'PageController?' is nullable and 'ScrollController' isn't.
```

**Comment by JgomesAT** [comment]
I have the same problem, can you update the plugin fading_edge_scrollview-3.0.0 to last version fading_edge_scrollview 4.1.1

**Comment by hatim-essadeq** [comment]
i have the same issue, cant build the app, please to update the fading_edge_scrollview to ^4.1.1.
thanks.

**Comment by realitymolder** [comment]
> i have the same issue, cant build the app, please to update the fading_edge_scrollview to ^4.1.1. thanks.

done! please use the following: 
```
  marquee:
    git:
      url: https://github.com/MarcelGarus/marquee.git
      ref: "master"
      ```
